# Generated by Django 5.0.7 on 2024-08-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="contact_no",
        ),
        migrations.AddField(
            model_name="contact",
            name="subject",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
