# Generated by Django 5.0.7 on 2024-08-08 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_contact_contact_no_contact_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="added_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
