# Generated by Django 5.0.7 on 2024-08-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="contact_number",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
